# Generated by Django 5.2.4 on 2025-08-27 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_db', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveSmallIntegerField(help_text='Minimum percentage (inclusive)')),
                ('label', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in admin')),
            ],
            options={
                'ordering': ['-min_score'],
                'unique_together': {('min_score', 'label')},
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Numeric score or percentage (0-100)', max_digits=5)),
                ('grade_label', models.CharField(blank=True, max_length=10)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college_db.academicyear')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college_db.course')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='college_db.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'academic_year')},
            },
        ),
    ]
