# Generated by Django 5.2.4 on 2025-08-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_db', '0002_gradingscale_studentgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='description',
        ),
        migrations.AddField(
            model_name='fee',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
