# Generated by Django 5.2.4 on 2025-08-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_db', '0003_remove_fee_description_fee_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assigned_courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='timetable',
            field=models.TextField(blank=True, null=True),
        ),
    ]
