# Generated by Django 5.2.4 on 2025-08-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_db', '0004_staff_assigned_courses_staff_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
