# Generated by Django 5.2.4 on 2025-08-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_db', '0005_alter_course_department_alter_staff_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
