# Generated by Django 5.2.4 on 2025-08-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_db', '0006_alter_student_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
    ]
