# Generated by Django 5.2.4 on 2025-08-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_db', '0007_alter_enrollment_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g., 2024-2025, First Year, etc.', max_length=20, null=True),
        ),
    ]
