# Generated by Django 5.2.4 on 2025-09-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_db', '0008_alter_studentgrade_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
